### ISSUE TITLE
STS Temporary Credentials

### ISSUE THREAD

**Issue by peter-friedland-bose** [uktrade/jupyters3#10]
please consider supporting STS temporary tokens including aws_session_token when signing your headers

**Comment by michalc** [comment]
@peter-friedland-bose Can you give a bit more info on context, and if anything from https://github.com/uktrade/jupyters3/issues/9 would help? My suspicion is that this _is_ supported, but perhaps by writing your own `JupyterS3Authentication` subclass.

**Comment by peter-friedland-bose** [comment]
To be clearer, I provide the set of temporary STS tokens including session_token obtained upstream . So this isn't a case where I'm needing to use an EC2 instance profile (IAM role).

**Comment by michalc** [comment]
> So this isn't a case where I'm needing to use an EC2 instance profile (IAM role).

Understood (I think...), but it sounds like the only difference is where the credentials + token + expiry, come from? So something like the below should work, but filling in the `...` with however you get the credentials + token + expiry?

```
import datetime
import json

from jupyters3 import JupyterS3Authentication
from tornado import gen
from tornado.httpclient import (
    AsyncHTTPClient,
    HTTPError as HTTPClientError,
    HTTPRequest,
)

class MyCredentialsSupplier(JupyterS3Authentication):
    role_name = Unicode(config=True)
    aws_access_key_id = Unicode()
    aws_secret_access_key = Unicode()
    pre_auth_headers = Dict()
    expiration = Datetime()

    @gen.coroutine
    def get_credentials(self):
        now = datetime.datetime.now()

        if now > self.expiration:
            self.aws_access_key_id = ...
            self.aws_secret_access_key = ...
            self.pre_auth_headers = {
                'x-amz-security-token': ...,
            }
            self.expiration = ...

        return AwsCreds(
            access_key_id=self.aws_access_key_id,
            secret_access_key=self.aws_secret_access_key,
            pre_auth_headers=self.pre_auth_headers,
        )
```

**Comment by michalc** [comment]
Closing since I believe this can be achieved without a code change to JupyterS3. Feel free to reopen though.
