### ISSUE TITLE
Access to push a really small branch for a code review.

### ISSUE THREAD

**Issue by calvin-booking** [uktrade/jupyters3#17]
Hello,

I wanted to push a really small branch for a code review.  May I please have access?

Thanks a lot.

**Comment by michalc** [comment]
Hi @calvin-booking,

You should be able to fork this repo, and create a pull request from the fork.

Thanks,

Michal

**Comment by calvin-booking** [comment]
> Hi @calvin-booking,
> 
> You should be able to fork this repo, and create a pull request from the fork.
> 
> Thanks,
> 
> Michal

Thanks I'll do that.
