### ISSUE TITLE
Small issue in docs - misspelling

### ISSUE THREAD

**Issue by JosCline** [uktrade/jupyters3#5]
FYI - You're missing a "y" in jupyters3 in the part of your instructions in your Read.me, as well as, on https://pypi.org/project/jupyters3/

"from jupters3 import JupyterS3, JupyterS3SecretAccessKeyAuthentication"

BTW, +1 for this. It's a great alternative to s3contents.

**Comment by michalc** [comment]
Thanks, and fixed!
