### ISSUE TITLE
feature request: support iam roles authentication

### ISSUE THREAD

**Issue by ophiry** [uktrade/jupyters3#9]

**Comment by michalc** [comment]
Hi @ophiry,

This is already possible if running in ECS using `JupyterS3ECSRoleAuthentication`. Can I check what environment you would like role-based authentication?

Thanks,

Michal

**Comment by ophiry** [comment]
I'm referring to regular EC2 instances.
basically in most cases just omitting explicit credential use works, as the AWS library falls back to using the metadata service to lookup the credentials.

based on the code, the ECS plugin isn't compatible - on EC2 the variable AWS_CONTAINER_CREDENTIALS_RELATIVE_URI isn't set, and the metadata service is on http://169.254.169.254/ and not http://169.254.170.2/

trying to use the plugin gives the error: 
KeyError: 'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI' because of the missing environment variable

**Comment by michalc** [comment]
> I'm referring to regular EC2 instances.

Ah: this has not been a use case of JupyterS3 for us, so it was never coded up.

Looking at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials you might be able to code up a class to do it yourself. Something like the below should work (note: this has not been tested!)

```python
import datetime
import json

from jupyters3 import JupyterS3Authentication
from tornado import gen
from tornado.httpclient import (
    AsyncHTTPClient,
    HTTPError as HTTPClientError,
    HTTPRequest,
)

class JupyterS3EC2RoleAuthentication(JupyterS3Authentication):

    role_name = Unicode(config=True)
    aws_access_key_id = Unicode()
    aws_secret_access_key = Unicode()
    pre_auth_headers = Dict()
    expiration = Datetime()

    @gen.coroutine
    def get_credentials(self):
        now = datetime.datetime.now()

        if now > self.expiration:
            request = HTTPRequest('http://169.254.169.254/latest/meta-data/iam/security-credentials/' + self.role_name, method='GET')
            creds = json.loads((yield AsyncHTTPClient().fetch(request)).body.decode('utf-8'))
            self.aws_access_key_id = creds['AccessKeyId']
            self.aws_secret_access_key = creds['SecretAccessKey']
            self.pre_auth_headers = {
                'x-amz-security-token': creds['Token'],
            }
            self.expiration = datetime.datetime.strptime(creds['Expiration'], '%Y-%m-%dT%H:%M:%SZ')

        return AwsCreds(
            access_key_id=self.aws_access_key_id,
            secret_access_key=self.aws_secret_access_key,
            pre_auth_headers=self.pre_auth_headers,
        )
```
Used as
```python
c.JupyterS3.authentication_class = JupyterS3EC2RoleAuthentication
c.JupyterS3EC2RoleAuthentication = the_role_name_of_the_ec2instance

**Comment by michalc** [comment]
Closing since I believe the feature can be coded up without a change to JupyterS3
